### PR TITLE
Changes to get the loctool to run on project

### PR DESCRIPTION
**Pull request by ehoogerbeets**
- added project.json to configure the loctool
- modified package.json for the packages that the loctool needs to localize github flavored markdown
- added things to the .gitignore so that the artifacts of the localization process are not accidentally checked in

### CODE REVIEW

**Comment by cbetta** [comment]
@ehoogerbeets thanks for the PR. All looks good to me, but just wondering if we need to add this code to this project. For the API spec we didn't have to add any files, yet for this we do. Can you elaborate on the difference?

Additionally, can we move the dependencies to be regular dependencies? AS this project publishes markdown/JSON there's no real need for a split in dependencies.

**Comment by ehoogerbeets** [comment]
These files are not strictly required, no, because they can be placed temporarily in a clone of this repo just before running but the loctool. The project.json configures how the localization tool extracts and generates strings in the files in this repo. As such, this is meta-info about this project in the same way that package.json is meta-info about the project.

We can move the dependencies to just "dependencies" if this project never forms a package that is installed on its own. They are only need to run the loctool.

**Comment by cbetta** [comment]
Let's move it to dependencies, and keep the rest in this repo. This whole project doesn't get packaged ever, so I'm not too worried about splitting dependencies.

**Comment by cbetta** [comment]
Changes merged.

**Pull request closed without merging**
